package classes;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ilan Margolis
 * @date   2020-05-04
 * 
 */
public class TelaPrincipal extends javax.swing.JDialog {
    // CONSTANTES
    final int EDT_LIMPA   = 0;
    final int EDT_MOSTRA  = 1;
    final int EDT_PROCURA = 2;
    
    final int ST_DERROTA = -1;
    final int ST_JOGANDO = 0;
    final int ST_VITORIA = 1;
    
    // VARIÁVEIS
    int contAcertos, contErros;
    
    /**
     * CRIAR novo formulário TelaPrincipal
     */
    public TelaPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
               
        configuraBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlForca = new javax.swing.JPanel();
        imgForca = new javax.swing.JLabel();
        pnlPalavra = new javax.swing.JPanel();
        pnlTeclado = new javax.swing.JLayeredPane();
        btnI = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnInicar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jogo da Forca - By Ilan Margolis ©2020");
        setResizable(false);

        pnlForca.setVerifyInputWhenFocusTarget(false);

        imgForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca0.png"))); // NOI18N
        imgForca.setMaximumSize(new java.awt.Dimension(68, 73));
        imgForca.setMinimumSize(new java.awt.Dimension(68, 73));
        imgForca.setPreferredSize(new java.awt.Dimension(68, 73));

        javax.swing.GroupLayout pnlForcaLayout = new javax.swing.GroupLayout(pnlForca);
        pnlForca.setLayout(pnlForcaLayout);
        pnlForcaLayout.setHorizontalGroup(
            pnlForcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgForca, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );
        pnlForcaLayout.setVerticalGroup(
            pnlForcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForcaLayout.createSequentialGroup()
                .addComponent(imgForca, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPalavra.setEnabled(false);
        pnlPalavra.setFocusable(false);

        javax.swing.GroupLayout pnlPalavraLayout = new javax.swing.GroupLayout(pnlPalavra);
        pnlPalavra.setLayout(pnlPalavraLayout);
        pnlPalavraLayout.setHorizontalGroup(
            pnlPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPalavraLayout.setVerticalGroup(
            pnlPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlTeclado.setPreferredSize(new java.awt.Dimension(366, 130));

        btnI.setText("I");

        btnE.setText("E");

        btnL.setText("L");

        btnR.setText("R");

        btnW.setText("W");

        btnO.setText("O");

        btnP.setText("P");

        btnA.setText("A");

        btnS.setText("S");

        btnD.setText("D");

        btnF.setText("F");

        btnG.setText("G");

        btnQ.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        btnQ.setText("Q");

        btnH.setText("H");

        btnJ.setText("J");

        btnK.setText("K");

        btnT.setText("T");

        btnY.setText("Y");

        btnU.setText("U");

        btnZ.setText("Z");

        btnB.setText("B");

        btnN.setText("N");

        btnM.setText("M");

        btnX.setText("X");

        btnC.setText("C");

        btnV.setText("V");

        pnlTeclado.setLayer(btnI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnR, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnW, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnQ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnJ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnK, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnY, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnZ, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlTeclado.setLayer(btnV, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlTecladoLayout = new javax.swing.GroupLayout(pnlTeclado);
        pnlTeclado.setLayout(pnlTecladoLayout);
        pnlTecladoLayout.setHorizontalGroup(
            pnlTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTecladoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnQ)
                .addGap(6, 6, 6)
                .addComponent(btnW)
                .addGap(6, 6, 6)
                .addComponent(btnE)
                .addGap(6, 6, 6)
                .addComponent(btnR)
                .addGap(6, 6, 6)
                .addComponent(btnT)
                .addGap(6, 6, 6)
                .addComponent(btnY)
                .addGap(6, 6, 6)
                .addComponent(btnU)
                .addGap(6, 6, 6)
                .addComponent(btnI)
                .addGap(6, 6, 6)
                .addComponent(btnO)
                .addGap(6, 6, 6)
                .addComponent(btnP))
            .addGroup(pnlTecladoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnA)
                .addGap(6, 6, 6)
                .addComponent(btnS)
                .addGap(6, 6, 6)
                .addComponent(btnD)
                .addGap(6, 6, 6)
                .addComponent(btnF)
                .addGap(6, 6, 6)
                .addComponent(btnG)
                .addGap(6, 6, 6)
                .addComponent(btnH)
                .addGap(6, 6, 6)
                .addComponent(btnJ)
                .addGap(6, 6, 6)
                .addComponent(btnK)
                .addGap(6, 6, 6)
                .addComponent(btnL))
            .addGroup(pnlTecladoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnZ)
                .addGap(8, 8, 8)
                .addComponent(btnX)
                .addGap(6, 6, 6)
                .addComponent(btnC)
                .addGap(6, 6, 6)
                .addComponent(btnV)
                .addGap(6, 6, 6)
                .addComponent(btnB)
                .addGap(6, 6, 6)
                .addComponent(btnN)
                .addGap(6, 6, 6)
                .addComponent(btnM))
        );
        pnlTecladoLayout.setVerticalGroup(
            pnlTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTecladoLayout.createSequentialGroup()
                .addGroup(pnlTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQ)
                    .addComponent(btnW)
                    .addComponent(btnE)
                    .addComponent(btnR)
                    .addComponent(btnT)
                    .addComponent(btnY)
                    .addComponent(btnU)
                    .addComponent(btnI)
                    .addComponent(btnO)
                    .addComponent(btnP))
                .addGap(6, 6, 6)
                .addGroup(pnlTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA)
                    .addComponent(btnS)
                    .addComponent(btnD)
                    .addComponent(btnF)
                    .addComponent(btnG)
                    .addComponent(btnH)
                    .addComponent(btnJ)
                    .addComponent(btnK)
                    .addComponent(btnL))
                .addGap(6, 6, 6)
                .addGroup(pnlTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZ)
                    .addComponent(btnX)
                    .addComponent(btnC)
                    .addComponent(btnV)
                    .addComponent(btnB)
                    .addComponent(btnN)
                    .addComponent(btnM)))
        );

        btnInicar.setText("INICIAR O JOGO");
        btnInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTeclado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnInicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicarActionPerformed
        // TODO add your handling code here:
        inicializaJogo();
    }//GEN-LAST:event_btnInicarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal dialog = new TelaPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null); // centraliza formulário na tela
                dialog.setSize(440, 600); // fixa o tamanho do formulário
                dialog.setVisible(true);  // torna o fomulário visível              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnInicar;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel imgForca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlForca;
    private javax.swing.JPanel pnlPalavra;
    private javax.swing.JLayeredPane pnlTeclado;
    // End of variables declaration//GEN-END:variables

    
    // FUNÇÕES AUXILIARES        
    private void carregaImagemForca(int tipo) {
        imgForca.setIcon(new javax.swing.ImageIcon(getClass().
                         getResource("/imagens/forca" + tipo + ".png")));
    }
    
    private boolean componenteEdit(int op, String letra) {
        boolean flagUsouLetra = false;
        
        for (Component c : pnlPalavra.getComponents()) {
            if (c instanceof JTextField) {
                switch (op) {
                    case EDT_LIMPA:
                        // DESTROI Edits existentes
                        pnlPalavra.remove((JTextField) c);
                        break;
                    case EDT_MOSTRA:
                        // MOSTRA letras que faltavam
                        if (((JTextField) c).getForeground().equals(Color.white)) {
                            
                            ((JTextField) c).setForeground(Color.red);
                            ((JTextField) c).setBackground(Color.yellow);
                            
                        }   break;
                    case EDT_PROCURA:                        
                        if (((JTextField) c).getText().equals(letra)) {
                            if (((JTextField) c).getForeground().equals(Color.white)) {
                            
                                ((JTextField) c).setForeground(Color.black);
                            
                                contAcertos++;  
                                
                                pintaLetraTeclado(letra, Color.green);
                            }

                            flagUsouLetra = true;
                            
                        }   break;
                    default:
                        break;
                }
            }
        }
    
        return flagUsouLetra;
    }

    private void configuraBotoes() { // escutador das teclas alfabéticas
        // VERIFICA se a letra já foi utilizada
        ActionListener al = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String letra = e.getActionCommand();
                int status = ST_JOGANDO;
                
                if (pnlPalavra.getComponents().length > 0) { // só ativa teclado caso a palavra tenha sido sorteada
                    if (!isLetraUsada(letra)) {
                        boolean flagAcertouLetra = false;
                        
                        flagAcertouLetra = componenteEdit(EDT_PROCURA, letra);
                        
                        if (!flagAcertouLetra) {
                            pintaLetraTeclado(letra, Color.red);
                            
                            contErros++;
                            
                            carregaImagemForca(contErros); // carrega a imagem do enforcamento 
                        }
                    }

                    // VITÓRIA / DERROTA
                    if (contAcertos == pnlPalavra.getComponents().length) { // vitória
                        if (contErros > 0) { // liberta o boneco se tiver iniciado o enforcamento
                            carregaImagemForca(9);  
                        }
                        
                        status = ST_VITORIA;
                    } else if (contErros == 8) { // derrota
                        componenteEdit(EDT_MOSTRA, null);  // mostra as letras que faltam na palavra
                        
                        status = ST_DERROTA;
                    }
                }
                
                if (status != ST_JOGANDO) {
                    btnInicar.setEnabled(true);
                }
            }
        };
        
        // ADICIONA ActionListener para todos os botões do teclado
        for (Component c : pnlTeclado.getComponents()) {
            if (c instanceof JButton) {
                ((JButton) c).addActionListener(al);
            }
        }
    }       
    
    private void criaEditsLetras() { // sorteia a palavra e prepara edits para as letras
        Palavra palavra = new Palavra();
        String secreta = palavra.sortear();
        
        pnlPalavra.repaint();
        
        // CRIA os edits das letras da palavra secreta
        for (int i = 0; i < secreta.length(); i++) {
            String nome = "Letra" + Integer.toString(i);
            JTextField letra = new JTextField(nome);
            letra.setText(secreta.substring(i, i + 1));
            letra.setBounds(34 * i + 5, 5, 34, 34);
            letra.setFont(new Font("dialog", Font.BOLD, 17));
            letra.setHorizontalAlignment(letra.CENTER);
            letra.setForeground(Color.white); // esconde a letra
            
            pnlPalavra.add(letra);

            letra.setVisible(true);
        }
    }

    private void inicializaJogo() { // inicializa a interface do jogo
        contAcertos = contErros = 0;
         
        componenteEdit(EDT_LIMPA, null);  
        
        pintaLetraTeclado("", Color.LIGHT_GRAY);
        
        carregaImagemForca(0);
        
        criaEditsLetras();
        
        btnInicar.setEnabled(false);
        
        pnlTeclado.requestFocus();
    }

    private boolean isLetraUsada(String letra) { // verifica se a letra já foi teclada
        boolean retorno = false;
        
        for (Component b : pnlTeclado.getComponents()) {
            if (b instanceof JButton) {
                if (((JButton) b).getText().equals(letra)) {
                    retorno = !((JButton) b).getBackground().equals(Color.LIGHT_GRAY);
                    
                    break;
                }
            }
        }
        
        return retorno;
    }
 
    private void pintaLetraTeclado(String letra, Color cor) { // responsável por pintar as teclas
        for (Component b : pnlTeclado.getComponents()) {
            if (b instanceof JButton) {
                if ((letra.equals("")) || (((JButton) b).getText().equals(letra))) {
                   ((JButton) b).setBackground(cor);
                   
                   ((JButton) b).setOpaque(letra.equals(""));
                }
            }
        }
    }   
}
